version: 2
workflows:
  version: 2
  workflow:
    jobs:
      - MacOS
      - Linux
jobs:
  MacOS:
    macos:
      xcode: "9.4"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-spm-deps-{{ checksum "Package.swift" }}
      - run:
          name: Build and Run SwiftDataLoader Tests
          no_output_timeout: 1800
          command: |
            swift package generate-xcodeproj --enable-code-coverage    
            xcodebuild -scheme SwiftDataLoader-Package -enableCodeCoverage YES test | xcpretty
      - save_cache:
          key: v1-spm-deps-{{ checksum "Package.swift" }}
          paths:
            - .build
  Linux:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-spm-deps-{{ checksum "Package.swift" }}
      - run:
          name: Copy Package file
          command: cp Package.swift res
      - run:
          name: Build and Run SwiftDataLoader Tests
          no_output_timeout: 1800
          command: |
            swift test -Xswiftc -DNOJSON
      - run:
          name: Restoring Package file
          command: mv res Package.swift
      - save_cache:
          key: v2-spm-deps-{{ checksum "Package.swift" }}
          paths:
            - .build